import {
  LayoutGrid,
  Beef,
  Cpu,
  Box,
  ShoppingCart,
  Factory,
  Wheat,
  Truck,
  FlaskConical,
  Scale,
  Receipt,
  Anchor,
  Egg,
  Maximize2,
  HeartPulse,
  Layers,
  MoveDown,
  Monitor,
  Gauge,
  Award,
  Microscope,
  Shield,
  Users,
  ShieldCheck,
  type LucideIcon,
} from "lucide-react";

export interface ProductItem {
  id: string;
  name: string;
  category:
    | "carnicos"
    | "etiquetadoras"
    | "empaque"
    | "comerciales"
    | "industriales"
    | "agropecuaria"
    | "ganadera"
    | "laboratorio";
  categoryName: string;
  categoryIcon: string;
  specs: string;
  image: string;
  badge: string;
  highlight: string;
  icon: LucideIcon;
  featureTag: string;
}

export interface CategoryItem {
  id: string;
  name: string;
  desc: string;
  icon: LucideIcon;
}

export const CATALOG_CATEGORIES: CategoryItem[] = [
  { id: "all", name: "Todas", desc: "Todo el catálogo", icon: LayoutGrid },
  { id: "carnicos", name: "Cárnicos & Charcutería", desc: "Molinos y rebanadoras", icon: Beef },
  { id: "etiquetadoras", name: "Etiquetadoras & IA", desc: "POS inteligentes", icon: Cpu },
  { id: "empaque", name: "Empaque al Vacío", desc: "Sellado industrial", icon: Box },
  { id: "comerciales", name: "Comerciales", desc: "Mostrador y tickets", icon: ShoppingCart },
  { id: "industriales", name: "Industriales", desc: "Plataformas y grúas", icon: Factory },
  { id: "agropecuaria", name: "Agropecuaria", desc: "Avícola y porcino", icon: Wheat },
  { id: "ganadera", name: "Ganadera", desc: "Bretes y barras", icon: Truck },
  { id: "laboratorio", name: "Laboratorio", desc: "Analíticas y precisión", icon: FlaskConical },
] as const;

export const CATALOG_PRODUCTS: ProductItem[] = [
  // ── 1. COMERCIALES 🛒 ──
  {
    id: "com-mostrador-30kg",
    name: "Balanza Digital de Mostrador Dialka 30kg",
    category: "comerciales",
    categoryName: "Comerciales",
    categoryIcon: "🛒",
    specs: "30 kg × 5 g · Doble display LED · Batería 100h",
    image: "/images/productos/comercial.jpg",
    badge: "Homologada SENCAMER",
    highlight: "Ideal para charcuterías, panaderías y minimarkets",
    icon: Scale,
    featureTag: "Doble Display",
  },
  {
    id: "com-ticketera-30kg",
    name: "Balanza Comercial con Impresión de Tickets",
    category: "comerciales",
    categoryName: "Comerciales",
    categoryIcon: "🛒",
    specs: "30 kg · Impresor térmico · 1.000 PLUs memorias",
    image: "/images/productos/com-ticketera-30kg.jpg",
    badge: "Punto de Venta",
    highlight: "Conexión Ethernet y RS-232 a sistemas de facturación",
    icon: Receipt,
    featureTag: "Ticket Térmico",
  },
  {
    id: "com-colgante-50kg",
    name: "Balanza Colgante Digital de 50kg",
    category: "comerciales",
    categoryName: "Comerciales",
    categoryIcon: "🛒",
    specs: "50 kg × 10 g · Gancho de acero inox · Display LCD",
    image: "/images/productos/com-colgante-50kg.jpg",
    badge: "Portátil",
    highlight: "Para pescaderías, carnicerías y mercados mayoristas",
    icon: Anchor,
    featureTag: "Gancho Inox",
  },
  {
    id: "com-mostrador-plana-15kg",
    name: "Balanza Plana de Mostrador 15kg Acero Inox",
    category: "comerciales",
    categoryName: "Comerciales",
    categoryIcon: "🛒",
    specs: "15 kg × 2 g · Plato acero 304 · Función tara/cómputo",
    image: "/images/sencamer/balanza-certificada.jpg",
    badge: "Acero Inox 304",
    highlight: "Resistente a líquidos, salmuera y fácil desinfección",
    icon: ShieldCheck,
    featureTag: "Grado Sanitario",
  },

  // ── 2. AGROPECUARIA 🌾 ──
  {
    id: "agro-aves-20kg",
    name: "Báscula Mecánica para Aves 20kg",
    category: "agropecuaria",
    categoryName: "Agropecuaria",
    categoryIcon: "🌾",
    specs: "20 kg · Plato cóncavo · Amortiguador de aleteo",
    image: "/images/productos/agropecuario.jpg",
    badge: "Sector Avícola",
    highlight: "Diseño ergonómico para galpones de engorde y beneficio",
    icon: Egg,
    featureTag: "Anti-Aleteo",
  },
  {
    id: "agro-porcinos-300kg",
    name: "Báscula Jaula para Porcinos 300kg",
    category: "agropecuaria",
    categoryName: "Agropecuaria",
    categoryIcon: "🌾",
    specs: "300 kg · Jaula con rejas · Indicador anti-movimiento",
    image: "/images/productos/agro-porcinos-300kg.jpg",
    badge: "Porcicultura",
    highlight: "Filtro de estabilización de peso para cerdos en movimiento",
    icon: Box,
    featureTag: "Filtro Dinámico",
  },
  {
    id: "agro-barras-2000kg",
    name: "Barras Pesadoras Portátiles 2.000kg (Par)",
    category: "agropecuaria",
    categoryName: "Agropecuaria",
    categoryIcon: "🌾",
    specs: "2.000 kg · 2 barras de 100 cm · Cable con malla de acero",
    image: "/images/productos/agro-barras-2000kg.jpg",
    badge: "Multi-Uso Campo",
    highlight: "Se instalan fácilmente bajo cualquier cajón o manga",
    icon: Maximize2,
    featureTag: "Portátil 2T",
  },
  {
    id: "agro-veterinaria-150kg",
    name: "Báscula Veterinaria para Mascotas y Menores",
    category: "agropecuaria",
    categoryName: "Agropecuaria",
    categoryIcon: "🌾",
    specs: "150 kg × 50 g · Perfil ultra bajo · Alfombra antideslizante",
    image: "/images/productos/agro-veterinaria-150kg.jpg",
    badge: "Clínicas y Fincas",
    highlight: "Función Hold para retención del peso en pantalla",
    icon: HeartPulse,
    featureTag: "Función Hold",
  },

  // ── 3. INDUSTRIALES 🏭 ──
  {
    id: "ind-plataforma-1500kg",
    name: "Plataforma de Piso Industrial 1.500kg (1.20×1.20m)",
    category: "industriales",
    categoryName: "Industriales",
    categoryIcon: "🏭",
    specs: "1.500 kg × 200 g · 4 Celdas IP67 · Chapa estriada",
    image: "/images/productos/industrial.jpg",
    badge: "Alto Tráfico",
    highlight: "Para almacenes de despacho, fábricas y paletas estándar",
    icon: Layers,
    featureTag: "4 Celdas IP67",
  },
  {
    id: "ind-grua-5000kg",
    name: "Báscula Colgante de Grúa 5.000kg para Puente",
    category: "industriales",
    categoryName: "Industriales",
    categoryIcon: "🏭",
    specs: "5.000 kg · Gancho giratorio 360° · Control inalámbrico",
    image: "/images/productos/ind-grua-5000kg.jpg",
    badge: "Carga Pesada",
    highlight: "Pantalla LED gigante visible a más de 25 metros de distancia",
    icon: Anchor,
    featureTag: "Gancho 360°",
  },
  {
    id: "ind-extraplana-inox",
    name: "Plataforma Extraplana Inox con Rampas",
    category: "industriales",
    categoryName: "Industriales",
    categoryIcon: "🏭",
    specs: "1.000 kg · Rampas incorporadas · Lavable a presión IP68",
    image: "/images/productos/ind-extraplana-inox.jpg",
    badge: "Grado Sanitario",
    highlight: "Para plantas procesadoras de alimentos y laboratorios",
    icon: MoveDown,
    featureTag: "Rampas Inox",
  },
  {
    id: "ind-indicador-d300",
    name: "Indicador Digital Industrial Dialka D-300",
    category: "industriales",
    categoryName: "Industriales",
    categoryIcon: "🏭",
    specs: "Carcasa Inox · Salida RS-232/485 · Filtro digital anti-vibración",
    image: "/images/productos/ind-indicador-d300.jpg",
    badge: "Terminal Inteligente",
    highlight: "Integración directa con impresoras, semáforos y PLC",
    icon: Monitor,
    featureTag: "RS-232/485",
  },

  // ── 4. LABORATORIO 🧪 ──
  {
    id: "lab-apolo-1000g",
    name: "Balanza Analítica Apolo Lab 1000g × 0.1g",
    category: "laboratorio",
    categoryName: "Laboratorio",
    categoryIcon: "🧪",
    specs: "1.000 g × 0.1 g · Cortaviento de vidrio · Plato inox",
    image: "/images/productos/analitico.jpg",
    badge: "Alta Precisión",
    highlight: "Calibración externa rápida y función conteo de piezas",
    icon: FlaskConical,
    featureTag: "Cortaviento",
  },
  {
    id: "lab-apolo-3000g",
    name: "Balanza de Precisión Apolo Lab 3000g × 0.1g",
    category: "laboratorio",
    categoryName: "Laboratorio",
    categoryIcon: "🧪",
    specs: "3.000 g × 0.1 g · Pantalla LCD backlight · Nivel burbuja",
    image: "/images/productos/lab-apolo-3000g.jpg",
    badge: "Control de Calidad",
    highlight: "Estabilización veloz en menos de 1.5 segundos",
    icon: Gauge,
    featureTag: "0.1g Resolución",
  },
  {
    id: "lab-ohaus-scout",
    name: "Balanza de Precisión Ohaus Scout 5000g × 1g",
    category: "laboratorio",
    categoryName: "Laboratorio",
    categoryIcon: "🧪",
    specs: "5.000 g × 1 g · Protección contra sobrecarga · Apilable",
    image: "/images/productos/lab-ohaus-scout.jpg",
    badge: "Ohaus Global",
    highlight: "Fabricación estadounidense con máxima resistencia al desgaste",
    icon: Award,
    featureTag: "Ohaus Original",
  },
  {
    id: "lab-semianalitica-8000g",
    name: "Balanza Semianalítica 8000g × 1g Dialka",
    category: "laboratorio",
    categoryName: "Laboratorio",
    categoryIcon: "🧪",
    specs: "8.000 g × 1 g · Salida de datos GLP/GMP · Modo porcentaje",
    image: "/images/productos/lab-semianalitica-8000g.jpg",
    badge: "Ensayos Químicos",
    highlight: "Para formulación precisa de mezclas e insumos industriales",
    icon: Microscope,
    featureTag: "Norma GLP/GMP",
  },

  // ── 5. GANADERA 🐂 ──
  {
    id: "gan-brete-3000kg",
    name: "Báscula Ganadera de Brete Individual 3.000kg",
    category: "ganadera",
    categoryName: "Ganadera",
    categoryIcon: "🐂",
    specs: "3.000 kg · Estructura galvanizada · Puertas guillotina",
    image: "/images/proyectos/bascula-ganadera.jpg",
    badge: "Pesaje Bovino",
    highlight: "Diseñada para mangas de vacunación y embarque en potrero",
    icon: Shield,
    featureTag: "Galvanizada",
  },
  {
    id: "gan-colectiva-5000kg",
    name: "Báscula Ganadera Colectiva 5.000kg (3.00×2.00m)",
    category: "ganadera",
    categoryName: "Ganadera",
    categoryIcon: "🐂",
    specs: "5.000 kg · Capacidad 6 a 8 reses · Chapa antideslizante",
    image: "/images/productos/gan-colectiva-5000kg.jpg",
    badge: "Lotes de Ganado",
    highlight: "Piso de madera dura tratada o chapa estriada antiresbalante",
    icon: Users,
    featureTag: "6-8 Reses",
  },
  {
    id: "gan-kit-brete",
    name: "Kit de Modernización Electrónica para Brete",
    category: "ganadera",
    categoryName: "Ganadera",
    categoryIcon: "🐂",
    specs: "4 Celdas shear beam · Indicador digital con batería 80h",
    image: "/images/productos/gan-kit-brete.jpg",
    badge: "Transformación Digital",
    highlight: "Convierte cualquier brete mecánico antiguo a pesaje digital",
    icon: Cpu,
    featureTag: "4 Celdas Beam",
  },
  {
    id: "gan-portatil-ruedas",
    name: "Báscula Ganadera Portátil Remolcable con Ruedas",
    category: "ganadera",
    categoryName: "Ganadera",
    categoryIcon: "🐂",
    specs: "2.500 kg · Sistema de tiro y ruedas abatibles para campo",
    image: "/images/alquiler/ejes-portatil.jpg",
    badge: "100% Móvil",
    highlight: "Traslado seguro entre potreros y fincas con tiro para camioneta",
    icon: Truck,
    featureTag: "Remolcable",
  },

  // ── 7. CÁRNICOS & CHARCUTERÍA 🥩 ──
  {
    id: "carn-molino-tk32",
    name: "Molino de Carne Industrial Techfood TK-32",
    category: "carnicos",
    categoryName: "Cárnicos",
    categoryIcon: "🥩",
    specs: "350 kg/h · Motor 1.5 kW (2 HP) · Reversa · Acero SUS304",
    image: "/images/productos/techfood-molino-tk32.png",
    badge: "350 kg/h Continuo",
    highlight: "Cabezal desmontable en acero inoxidable para carnicerías y supermercados",
    icon: Beef,
    featureTag: "Motor 1.5 kW",
  },
  {
    id: "carn-molino-tk42",
    name: "Molino de Carne de Alta Capacidad Techfood TK-42",
    category: "carnicos",
    categoryName: "Cárnicos",
    categoryIcon: "🥩",
    specs: "650 kg/h · Motor 3.0 kW (4 HP) · Reductor en baño de aceite",
    image: "/images/productos/techfood-molino-tk42.png",
    badge: "650 kg/h Frigorífico",
    highlight: "Diseñado para salas de desposte, frigoríficos y producción continua",
    icon: Beef,
    featureTag: "Uso Pesado",
  },
  {
    id: "carn-molino-cg22dm",
    name: "Molino Combinado con Rallador Techfood CG22DM",
    category: "carnicos",
    categoryName: "Cárnicos",
    categoryIcon: "🥩",
    specs: "Doble función: Molino #22 + Rallador queso/pan · Motor 1.1 kW",
    image: "/images/productos/techfood-molino-cg22dm.png",
    badge: "2 en 1 Multifunción",
    highlight: "Equipo multifunción que ahorra espacio en carnicerías, charcuterías y pizzerías",
    icon: Beef,
    featureTag: "2 en 1",
  },
  {
    id: "carn-rallador-cg55sh",
    name: "Rallador Industrial de Queso y Pan Techfood CG55SH",
    category: "carnicos",
    categoryName: "Cárnicos",
    categoryIcon: "🥩",
    specs: "40 kg/h · Motor 0.75 HP · Microswitch de seguridad",
    image: "/images/productos/techfood-rallador-cg55sh.png",
    badge: "Rendimiento 40kg/h",
    highlight: "Cilindro de acero inoxidable con palanca de presión de alta seguridad",
    icon: Box,
    featureTag: "Seguridad Activa",
  },
  {
    id: "carn-mezcladora-mm55dt",
    name: "Mezcladora de Carne y Embutidos Techfood MM55DT",
    category: "carnicos",
    categoryName: "Cárnicos",
    categoryIcon: "🥩",
    specs: "Tanque 28 L (20 kg) · Motor 550 W · Doble eje basculante",
    image: "/images/productos/techfood-mezcladora-mm55dt.png",
    badge: "Tanque 28 Litros",
    highlight: "Mezcla homogénea sin recalentar la masa de chorizos y embutidos",
    icon: Layers,
    featureTag: "Paletas Inox",
  },
  {
    id: "carn-mezcladora-mm75dt",
    name: "Mezcladora de Carne Industrial Techfood MM75DT 42L",
    category: "carnicos",
    categoryName: "Cárnicos",
    categoryIcon: "🥩",
    specs: "Tanque 42 L (35 kg) · Motor 750 W con reversa · Volteo manual 90°",
    image: "/images/productos/techfood-mezcladora-mm75dt.png",
    badge: "Capacidad 42 Litros",
    highlight: "Capacidad extendida para fábricas de embutidos, albóndigas y hamburguesas",
    icon: Layers,
    featureTag: "Capacidad 42L",
  },
  {
    id: "carn-ablandador-tr8s",
    name: "Tenderizadora y Ablandador de Carne Techfood TR8S",
    category: "carnicos",
    categoryName: "Cárnicos",
    categoryIcon: "🥩",
    specs: "Motor 550 W · Rodillos microdentados SUS304 · Alimentador seguro",
    image: "/images/productos/techfood-ablandador-tr8s.png",
    badge: "Grado Sanitario",
    highlight: "Ablanda cortes de carne sin desjugar ni romper la textura original",
    icon: Beef,
    featureTag: "Acero SUS304",
  },
  {
    id: "carn-rebanadora-300",
    name: "Rebanadora Industrial de Embutidos Techfood 300mm",
    category: "carnicos",
    categoryName: "Cárnicos",
    categoryIcon: "🥩",
    specs: "Disco 300 mm · Motor 250 W · Afilador doble incorporado",
    image: "/images/productos/techfood-rebanadora-300mm.png",
    badge: "Disco 300 mm",
    highlight: "Corte micrométrico regulable desde 0.2 a 15 mm en aluminio anodizado",
    icon: Beef,
    featureTag: "Corte Micrométrico",
  },
  {
    id: "carn-rebanadora-abm",
    name: "Rebanadora de Precisión Italiana ABM 250mm",
    category: "carnicos",
    categoryName: "Cárnicos",
    categoryIcon: "🥩",
    specs: "Disco 250 mm · Motor 1.2 HP · Fabricación 100% Italiana",
    image: "/images/productos/abm-rebanadora-250mm.png",
    badge: "Made in Italy",
    highlight: "Máxima suavidad de traslación del carro y precisión milimétrica en lonchas",
    icon: Award,
    featureTag: "Origen Italia",
  },
  {
    id: "carn-cuchilleria-lucky",
    name: "Cuchillería Profesional Carnicera Lucky Acero Alemán",
    category: "carnicos",
    categoryName: "Cárnicos",
    categoryIcon: "🥩",
    specs: "Acero Alemán 1.4116 · Mango Sanitized · Certificación NSF",
    image: "/images/productos/lucky-cuchilleria-chef.png",
    badge: "Certificación NSF",
    highlight: "Cuchillos carniceros, deshuesadores y fileteros de filo prolongado",
    icon: ShieldCheck,
    featureTag: "Acero Alemán",
  },
  {
    id: "carn-cuchillas-molino",
    name: "Cuchillas Profesionales para Molinos Techfood / Lucky",
    category: "carnicos",
    categoryName: "Cárnicos",
    categoryIcon: "🥩",
    specs: "Acero templado de alta dureza · Medidas para bocas #12, #22 y #32",
    image: "/images/productos/lucky-cuchillas-molino.png",
    badge: "Repuesto Genuino",
    highlight: "Filo autoafilable de alto rendimiento para molienda limpia y sin fricción térmica",
    icon: Award,
    featureTag: "Acero Especial",
  },
  {
    id: "carn-molde-hamburguesa",
    name: "Prensadora y Moldeadora de Hamburguesas Techfood",
    category: "carnicos",
    categoryName: "Cárnicos",
    categoryIcon: "🥩",
    specs: "Diámetro 100/130 mm · Acero Inox · Dispensador de separadores",
    image: "/images/productos/techfood-molde-hamburguesa.png",
    badge: "Estandarización",
    highlight: "Garantiza peso y diámetro uniforme en cada porción de hamburguesa",
    icon: Box,
    featureTag: "Manual Rápido",
  },
  {
    id: "carn-pica-papas",
    name: "Cortadora Industrial de Papas a la Francesa Techfood",
    category: "carnicos",
    categoryName: "Cárnicos",
    categoryIcon: "🥩",
    specs: "Cuchillas 9 y 12 mm en acero inoxidable · Palanca multiplicadora",
    image: "/images/productos/techfood-pica-papas.png",
    badge: "Corte en Bloque",
    highlight: "Corte rápido de vegetales y papas con un solo movimiento de palanca",
    icon: Box,
    featureTag: "Cuchillas Inox",
  },
  {
    id: "carn-tablas-corte",
    name: "Tablas de Corte Sanitarias Antimicrobianas Techfood FDA",
    category: "carnicos",
    categoryName: "Cárnicos",
    categoryIcon: "🥩",
    specs: "Polietileno alta densidad PEAD · Espesores 1/2\" y 1\" · Norma FDA",
    image: "/images/productos/techfood-tablas-corte-fda.png",
    badge: "Aprobado FDA",
    highlight: "Superficie higiénica libre de poros que previene contaminación cruzada",
    icon: ShieldCheck,
    featureTag: "Grado Sanitario",
  },

  // ── 8. ETIQUETADORAS & INTELIGENCIA ARTIFICIAL 🤖 ──
  {
    id: "etiq-rongta-ia-win",
    name: "Balanza POS Etiquetadora con IA Rongta IA-Y3L (Windows)",
    category: "etiquetadoras",
    categoryName: "Etiquetadoras & IA",
    categoryIcon: "🤖",
    specs: "15/30 kg DUAL · Cámara IA 2.0 MP · Pantalla táctil 15.6\" HD · Windows",
    image: "/images/productos/rongta-ia-y3l-win.png",
    badge: "Reconocimiento con IA",
    highlight: "Identifica frutas, hortalizas y víveres visualmente en menos de 0.2 segundos",
    icon: Cpu,
    featureTag: "Cámara IA 2.0MP",
  },
  {
    id: "etiq-rongta-ia-android",
    name: "Balanza POS Inteligente Rongta IA-Y3L (Android)",
    category: "etiquetadoras",
    categoryName: "Etiquetadoras & IA",
    categoryIcon: "🤖",
    specs: "15/30 kg · Procesador Quad-Core · Pantalla 15.6\" · Android OS",
    image: "/images/productos/rongta-ia-y3l-android.png",
    badge: "Sistema Android",
    highlight: "Arquitectura flexible compatible con apps POS modernas y servicios en la nube",
    icon: Cpu,
    featureTag: "Android POS",
  },
  {
    id: "etiq-rongta-rls1100c",
    name: "Balanza Etiquetadora de Autoservicio Rongta RLS1100C",
    category: "etiquetadoras",
    categoryName: "Etiquetadoras & IA",
    categoryIcon: "🏷️",
    specs: "30 kg × 5 g · 10.000 PLU · Ethernet + RS232 · Imprime Códigos QR/EAN",
    image: "/images/productos/rongta-rls1100c.png",
    badge: "Top Ventas Retail",
    highlight: "Emisión de etiquetas térmicas personalizables para charcuterías y supermercados",
    icon: Receipt,
    featureTag: "10.000 PLU",
  },
  {
    id: "etiq-rongta-rls1100b",
    name: "Balanza Etiquetadora Comercial Rongta RLS1100B",
    category: "etiquetadoras",
    categoryName: "Etiquetadoras & IA",
    categoryIcon: "🏷️",
    specs: "15/30 kg · Teclado rápido 112 accesos · Visor alfanumérico doble",
    image: "/images/productos/rongta-rls1100b.png",
    badge: "Homologada SENCAMER",
    highlight: "Resistente a ambientes húmedos con cajón de papel térmico de recarga frontal",
    icon: Receipt,
    featureTag: "112 Teclas Directas",
  },
  {
    id: "etiq-rongta-rls1550p",
    name: "Balanza Etiquetadora de Torre Elevada Rongta RLS1550P",
    category: "etiquetadoras",
    categoryName: "Etiquetadoras & IA",
    categoryIcon: "🏷️",
    specs: "30 kg × 5 g · Impresión 90 mm/s · 8 vendedores simultáneos · Torre LED",
    image: "/images/productos/rongta-rls1550p.png",
    badge: "Torre Ergonómica",
    highlight: "Display elevado visible para el cliente sobre mostradores altos de atención",
    icon: Receipt,
    featureTag: "8 Vendedores",
  },
  {
    id: "etiq-rongta-rls1330",
    name: "Balanza Colgante Etiquetadora Rongta RLS1330",
    category: "etiquetadoras",
    categoryName: "Etiquetadoras & IA",
    categoryIcon: "🏷️",
    specs: "30 kg · Carcasa suspendida de acero inoxidable · Impresión EAN/QR",
    image: "/images/productos/rongta-rls1330.png",
    badge: "Suspensión Aérea",
    highlight: "Diseño colgante que previene ingreso de líquidos en pescaderías y carnicerías",
    icon: Anchor,
    featureTag: "Antiderrame Aéreo",
  },
  {
    id: "etiq-rongta-pos-c1",
    name: "Balanza POS de Mostrador para Facturación Rongta C1",
    category: "etiquetadoras",
    categoryName: "Etiquetadoras & IA",
    categoryIcon: "🖥️",
    specs: "15/30 kg DUAL · Visor extendible 3 caras · Puertos USB, RS232 y WiFi",
    image: "/images/productos/rongta-pos-c1.png",
    badge: "Integración de Cajas",
    highlight: "Conexión directa con software Saint, Valery, Profit Plus y Stellar",
    icon: Monitor,
    featureTag: "USB / RS232 / WiFi",
  },

  // ── 9. EMPAQUE AL VACÍO & TERMOSELLADO 📦 ──
  {
    id: "emp-vacio-dz400",
    name: "Empacadora al Vacío Industrial de Campana Techfood DZ-400",
    category: "empaque",
    categoryName: "Empaque al Vacío",
    categoryIcon: "📦",
    specs: "Doble barra 40 cm · Bomba 20 m³/h · Acero Inoxidable · Vacío 99.9%",
    image: "/images/productos/techfood-dz400-vacio.png",
    badge: "Doble Barra 40cm",
    highlight: "Conserva carnes, pescados y embutidos hasta 5 veces más tiempo sin deshidratar",
    icon: Box,
    featureTag: "Bomba 20 m³/h",
  },
  {
    id: "emp-vacio-dz300b",
    name: "Empacadora al Vacío de Sobremesa Techfood DZ-300B",
    category: "empaque",
    categoryName: "Empaque al Vacío",
    categoryIcon: "📦",
    specs: "Barra de sellado 30 cm · Ciclos de 10 a 25 s · Gabinete en Acero Inox",
    image: "/images/productos/techfood-dz300b-vacio.png",
    badge: "Sobremesa Inox",
    highlight: "Tamaño compacto ideal para charcuterías, bodegones, restaurantes y laboratorios",
    icon: Box,
    featureTag: "Control Digital",
  },
  {
    id: "emp-termoselladora-45",
    name: "Termoselladora para Film de Alimentos Techfood 45cm",
    category: "empaque",
    categoryName: "Empaque al Vacío",
    categoryIcon: "📦",
    specs: "Ancho película 45 cm · Placa de teflón caliente · Regulador 0 a 160°C",
    image: "/images/productos/techfood-termoselladora-45cm.png",
    badge: "Sellado Continuo",
    highlight: "Embalaje rápido con plástico stretch para bandejas de carne, quesos y frutas",
    icon: Layers,
    featureTag: "Placa Térmica",
  },

  // ── 10. NUEVOS EQUIPOS COMERCIALES E INDUSTRIALES TECHFOOD ⚖️ ──
  {
    id: "com-techfood-jl918",
    name: "Balanza de Mostrador Antiderrame Techfood JL-918",
    category: "comerciales",
    categoryName: "Comerciales",
    categoryIcon: "🛒",
    specs: "15/30 kg · Batería 180 hrs · Doble visor cliente/vendedor con luz LED",
    image: "/images/productos/techfood-jl918.png",
    badge: "Batería 180 Horas",
    highlight: "Chasis hermético contra líquidos con una autonomía récord ante fallas eléctricas",
    icon: Scale,
    featureTag: "Batería 180h",
  },
  {
    id: "com-techfood-jl918-led",
    name: "Balanza Comercial de Mostrador Techfood JL-918 LED",
    category: "comerciales",
    categoryName: "Comerciales",
    categoryIcon: "🛒",
    specs: "15/30 kg · Teclado plano pulsador · Batería 180 hrs · Doble pantalla LED",
    image: "/images/productos/techfood-jl918-led.png",
    badge: "Plato Plano Duradero",
    highlight: "Teclado de pulsadores táctiles de alta durabilidad con 7 memorias de precio directo",
    icon: Scale,
    featureTag: "Teclado Pulsador",
  },
  {
    id: "com-techfood-ocsp",
    name: "Balanza Colgante con Canasta Inoxidable Techfood OCS-P",
    category: "comerciales",
    categoryName: "Comerciales",
    categoryIcon: "🛒",
    specs: "30 kg × 5 g · Bandeja honda profunda · Doble visor LCD",
    image: "/images/productos/techfood-ocsp-colgante.png",
    badge: "Homologada SENCAMER",
    highlight: "Especial para mercados municipales, verdulerías y venta de quesos al mayor",
    icon: Anchor,
    featureTag: "Bandeja Honda",
  },
  {
    id: "ind-techfood-jl11",
    name: "Balanza de Plataforma 300 kg con Columna Techfood JL-11",
    category: "industriales",
    categoryName: "Industriales",
    categoryIcon: "🏭",
    specs: "300 kg × 100 g · Bandeja 42.5 × 52 cm · Estructura tubular de alto impacto",
    image: "/images/productos/techfood-jl11-plataforma.png",
    badge: "300 kg Rudo",
    highlight: "Ideal para recepción de mercancía en almacenes, depósitos y distribuidoras",
    icon: Box,
    featureTag: "Plataforma 300kg",
  },
  {
    id: "ind-techfood-ocsm",
    name: "Balanza Colgante de Grúa Industrial Techfood OCS-M 1.000 kg",
    category: "industriales",
    categoryName: "Industriales",
    categoryIcon: "🏭",
    specs: "1.000 kg × 500 g · Carcasa de aluminio fundido · LED rojo gigante 4\"",
    image: "/images/productos/techfood-ocsm-grua.png",
    badge: "1 Tonelada",
    highlight: "Gancho de acero forjado con giro de 360° para carga aérea en galpones",
    icon: Anchor,
    featureTag: "Aluminio Fundido",
  },
  {
    id: "ind-techfood-tfx",
    name: "Plataforma Sanitaria Inoxidable Techfood TF-X 2.000 kg",
    category: "industriales",
    categoryName: "Industriales",
    categoryIcon: "🏭",
    specs: "90 × 90 cm · 2.000 kg · Acero Inox 4 mm · Indicador X1S Inox incluido",
    image: "/images/productos/techfood-tfx-inox.png",
    badge: "Acero Inox 4mm",
    highlight: "Construcción sanitaria anticorrosiva apta para lavados a presión continuos",
    icon: ShieldCheck,
    featureTag: "Acero Inox SUS304",
  },
  {
    id: "ind-techfood-tfx15",
    name: "Plataforma Sanitaria Extra Grande Techfood TF-X15 5.000 kg",
    category: "industriales",
    categoryName: "Industriales",
    categoryIcon: "🏭",
    specs: "150 × 150 cm · 5.000 kg · 4 Celdas Sharebeam 2T IP68 · Superficie diamantada",
    image: "/images/productos/techfood-tfx15-inox.png",
    badge: "5 Toneladas",
    highlight: "Superficie de gran formato para paletas completas y carga en zonas húmedas",
    icon: Factory,
    featureTag: "5.000 kg",
  },
  {
    id: "ind-techfood-x1s",
    name: "Indicador de Peso Digital en Acero Inoxidable Techfood X1S",
    category: "industriales",
    categoryName: "Industriales",
    categoryIcon: "🏭",
    specs: "Chasis Acero Inox IP68 · Pantalla LED de alta visibilidad · Puerto RS232",
    image: "/images/productos/techfood-indicador-x1s-inox.png",
    badge: "Protección IP68",
    highlight: "Resistente a la humedad y salpicaduras químicas con batería recargable",
    icon: Gauge,
    featureTag: "IP68 Inoxidable",
  },
  {
    id: "ind-techfood-x1s-abs",
    name: "Indicador de Peso Digital ABS Techfood X1S",
    category: "industriales",
    categoryName: "Industriales",
    categoryIcon: "🏭",
    specs: "Carcasa ABS alto impacto · 6 dígitos LED 40 mm · Batería 6V · Puerto RS232",
    image: "/images/productos/techfood-indicador-x1s-abs.png",
    badge: "Carcasa ABS",
    highlight: "Pantalla LED gigante de alta visibilidad con función especial de pesaje animal",
    icon: Gauge,
    featureTag: "Pesaje Animal",
  },
];
