import { RubroSector } from "./types";

export const RUBROS_DATA: RubroSector[] = [
  {
    id: "carniceria",
    title: "Carnicerías, Charcuterías & Frigoríficos",
    shortTitle: "Carnicerías & Cárnicos",
    emoji: "🥩",
    tagline: "Procesamiento y Pesaje de Alta Resistencia",
    description:
      "Soluciones integrales de grado alimentario para desposte, molienda continua, rebanado preciso y empaque hermético.",
    equipment: [
      {
        id: "molino-tk32",
        name: "Molino de Carne Industrial Techfood",
        model: "TK-32",
        specs: "350 kg/h · Doble velocidad con reversa · Acero Inox",
        badge: "Rendimiento Continuo",
        image: "/images/productos/techfood-molino-tk32.png",
      },
      {
        id: "rebanadora-300",
        name: "Rebanadora Industrial de Embutidos",
        model: "Techfood 300 mm",
        specs: "Disco 30 cm · Aluminio anodizado · Prensa Inox SUS304",
        badge: "Corte Preciso",
        image: "/images/productos/techfood-rebanadora-300mm.png",
      },
      {
        id: "balanza-ocsp",
        name: "Balanza Colgante con Canasta Frutas/Carnes",
        model: "Techfood OCS-P",
        specs: "30 kg × 5 g · Bandeja honda profunda · Pantalla LCD",
        badge: "Homologada SENCAMER",
        image: "/images/productos/techfood-ocsp-colgante.png",
      },
      {
        id: "ablandador-tr8s",
        name: "Tenderizadora / Ablandador de Carne",
        model: "Techfood TR8S",
        specs: "Potencia 550W · Acero Inoxidable · Sin esquinas afiladas",
        badge: "Grado Sanitario",
        image: "/images/productos/techfood-ablandador-tr8s.png",
      },
      {
        id: "cuchilleria-lucky",
        name: "Set de Cuchillería Profesional Carnicera",
        model: "Lucky German Steel",
        specs: "Deshuesador 6\", Chef 8\", Carnicero 12\" · Certificado NSF",
        badge: "Acero Alemán",
        image: "/images/productos/lucky-cuchilleria-chef.png",
      },
      {
        id: "mezcladora-mm55",
        name: "Mezcladora Industrial de Carne",
        model: "Techfood MM55DT",
        specs: "Tanque 28 L (20 kg) · Motor 550W · Mezcla carne congelada",
        badge: "Alta Eficiencia",
        image: "/images/productos/techfood-mezcladora-mm55dt.png",
      },
    ],
  },
  {
    id: "supermercado",
    title: "Supermercados, Bodegones & Minimarkets",
    shortTitle: "Supermercados & Retail",
    emoji: "🛒",
    tagline: "Pesaje Inteligente y Automatización de Cajas",
    description:
      "Balanzas con Inteligencia Artificial, impresión rápida de tickets/etiquetas QR y comunicación con sistemas administrativos.",
    equipment: [
      {
        id: "balanza-ia-y3l",
        name: "Balanza POS Etiquetadora con IA y Cámara",
        model: "Rongta IA-Y3L",
        specs: "15/30 kg DUAL · Cámara 2.0 MP con IA · Pantalla 15.6\" táctil",
        badge: "Reconocimiento IA",
        image: "/images/productos/rongta-ia-y3l-win.png",
      },
      {
        id: "etiquetadora-rls1100c",
        name: "Balanza Etiquetadora de Mostrador y Ticket",
        model: "Rongta RLS1100C",
        specs: "30 kg · Memoria 10.000 productos · Ethernet + Serial · EAN128/QR",
        badge: "Top Ventas",
        image: "/images/productos/rongta-rls1100c.png",
      },
      {
        id: "balanza-pos-c1",
        name: "Balanza POS de Mostrador para Puntos de Venta",
        model: "Rongta C1",
        specs: "15/30 kg DUAL · Display extendible LED · USB / RS232 / WiFi",
        badge: "Sistemas Administrativos",
        image: "/images/productos/rongta-pos-c1.png",
      },
      {
        id: "mostrador-jl918",
        name: "Balanza de Mostrador PPI Antiderrame",
        model: "Techfood JL-918",
        specs: "15/30 kg · Batería 180 hrs · Doble visor cliente/vendedor",
        badge: "Autonomía 180h",
        image: "/images/productos/techfood-jl918.png",
      },
      {
        id: "etiquetadora-torre",
        name: "Balanza Etiquetadora con Torre Flotante",
        model: "Rongta RLS1550P",
        specs: "30 kg · Impresión 90 mm/s · 8 vendedores · Cajero flotante",
        badge: "Torre Elevada",
        image: "/images/productos/rongta-rls1550p.png",
      },
    ],
  },
  {
    id: "agroindustria",
    title: "Agroindustria, Silos & Ganadería",
    shortTitle: "Agroindustria & Campo",
    emoji: "🌾",
    tagline: "Pesaje Pesado para Cosechas, Silos y Ganado",
    description:
      "Básculas camioneras, plataformas de piso de 2 a 5 toneladas y pesaje por ejes para trabajo continuo en faenas agrícolas.",
    equipment: [
      {
        id: "plataforma-tfx15",
        name: "Plataforma de Piso Inoxidable 5.000 kg",
        model: "Techfood TF-X15",
        specs: "150 × 150 cm · 4 Celdas Sharebeam 2T IP68 · Función animal",
        badge: "Carga Pesada 5T",
        image: "/images/productos/techfood-tfx15-inox.png",
      },
      {
        id: "plataforma-jl11",
        name: "Balanza de Plataforma 300 kg con Columna",
        model: "Techfood JL-11",
        specs: "300 kg × 100 g · Bandeja 42.5 × 52 cm · Batería 180 hrs",
        badge: "Homologada SENCAMER",
        image: "/images/productos/techfood-jl11-plataforma.png",
      },
      {
        id: "plataforma-tfx",
        name: "Plataforma Sanitaria Inox 2.000 kg",
        model: "Techfood TF-X",
        specs: "90 × 90 cm · Acero Inox 4 mm · Indicador LED X1S incluido",
        badge: "Acero Inox 4mm",
        image: "/images/productos/techfood-tfx-inox.png",
      },
      {
        id: "celdas-shear",
        name: "Juego de Celdas de Carga Shear Beam",
        model: "Techfood 2T / 500kg",
        specs: "Protección hermética IP68 · Clase de precisión C3 · Cable 6 hilos",
        badge: "Repuesto Genuino",
        image: "/images/productos/ind-extraplana-inox.jpg",
      },
      {
        id: "alquiler-portatil",
        name: "Báscula Camionera Portátil por Ejes 40T",
        model: "Dialka PortaWeigh",
        specs: "40 Toneladas · Módulos extraplanos transportables para zafra",
        badge: "Venta o Alquiler",
        image: "/images/alquiler/ejes-portatil.jpg",
      },
    ],
  },
  {
    id: "gastronomia",
    title: "Restaurantes, Panaderías & Alimentos",
    shortTitle: "Gastronomía & Panadería",
    emoji: "🍽️",
    tagline: "Empaque al Vacío y Porcionado Profesional",
    description:
      "Equipos de conservación al vacío, control exacto de porciones e higiene certificada para cocinas comerciales.",
    equipment: [
      {
        id: "vacio-dz400",
        name: "Empacadora al Vacío Industrial de Campana",
        model: "Techfood DZ-400",
        specs: "Doble barra sellado 40 cm · Bomba 750W · Acero Inoxidable",
        badge: "Doble Barra 40cm",
        image: "/images/productos/techfood-dz400-vacio.png",
      },
      {
        id: "vacio-dz300b",
        name: "Empacadora al Vacío de Sobremesa",
        model: "Techfood DZ-300B",
        specs: "Barra sellado 30 cm · Tiempo 10/20 seg · Cámara en acero inoxidable",
        badge: "Compacta & Rápida",
        image: "/images/productos/techfood-dz300b-vacio.png",
      },
      {
        id: "termoselladora-45",
        name: "Termoselladora para Film de Alimentos",
        model: "Techfood 45 cm",
        specs: "Ancho máximo 45 cm · Control de temperatura 0-160°C · Inox",
        badge: "Sellado Continuo",
        image: "/images/productos/techfood-termoselladora-45cm.png",
      },
      {
        id: "rallador-cg55sh",
        name: "Rallador Industrial de Queso y Pan",
        model: "Techfood CG55SH",
        specs: "Potencia 0.75 HP · Parada de seguridad automática · Acero Inox",
        badge: "Alto Rendimiento",
        image: "/images/productos/techfood-rallador-cg55sh.png",
      },
      {
        id: "rebanadora-abm",
        name: "Rebanadora Italiana de Precisión",
        model: "ABM 250 mm",
        specs: "Disco 25 cm · Motor 1.2 HP · Cuerpo aluminio anodizado",
        badge: "Importación Italiana",
        image: "/images/productos/abm-rebanadora-250mm.png",
      },
      {
        id: "tablas-fda",
        name: "Tablas de Corte Sanitarias Antimicrobianas",
        model: "Techfood FDA",
        specs: "Polietileno de alta densidad · No absorbe olores · Hasta 2 metros",
        badge: "Certificación FDA",
        image: "/images/productos/techfood-tablas-corte-fda.png",
      },
    ],
  },
  {
    id: "laboratorio",
    title: "Laboratorios, Farmacias & Química",
    shortTitle: "Laboratorio & Farmacia",
    emoji: "🧪",
    tagline: "Metrología Analítica y Acreditación Legal",
    description:
      "Balanzas de alta precisión con trazabilidad metrológica para formulaciones, control de calidad y auditorías.",
    equipment: [
      {
        id: "lab-ohaus-scout",
        name: "Balanza de Precisión Ohaus Scout Pro",
        model: "Ohaus SPX",
        specs: "600 g × 0.01 g · Calibración digital · Pantalla retroiluminada",
        badge: "Marca Global Ohaus",
        image: "/images/productos/lab-ohaus-scout.jpg",
      },
      {
        id: "lab-apolo-3000",
        name: "Balanza Semianalítica Apolo Lab",
        model: "Apolo 3000g",
        specs: "3.000 g × 0.1 g · Plato acero inoxidable · Conexión RS-232",
        badge: "Trazable SENCAMER",
        image: "/images/productos/lab-apolo-3000g.jpg",
      },
      {
        id: "lab-analitica-8000",
        name: "Balanza de Laboratorio para Dosificación",
        model: "Apolo Lab 8000",
        specs: "8.000 g × 1 g · Cortavientos y pesaje porcentual",
        badge: "Alta Capacidad Lab",
        image: "/images/productos/lab-semianalitica-8000g.jpg",
      },
      {
        id: "certificacion-sencamer-lab",
        name: "Certificado de Calibración con Masas Clase F1",
        model: "Servicio Metrológico",
        specs: "Pruebas de excentricidad, repetibilidad e incertidumbre",
        badge: "Validez Oficial",
        image: "/images/sencamer/balanza-certificada.jpg",
      },
    ],
  },
  {
    id: "logistica",
    title: "Industria Pesada, Almacenes & Logística",
    shortTitle: "Industria & Almacén",
    emoji: "🏭",
    tagline: "Control de Carga, Paletas y Despacho Masivo",
    description:
      "Pesaje aéreo por grúa, básculas de plataforma empotradas y software para auditoría de inventario.",
    equipment: [
      {
        id: "grua-ocsm-1000",
        name: "Balanza Colgante Industrial tipo Grúa 1.000 kg",
        model: "Techfood OCS-M",
        specs: "1.000 kg × 500 g · Dígitos LED gigantes 4\" · Gancho giratorio",
        badge: "Uso Rudo Industrial",
        image: "/images/productos/techfood-ocsm-grua.png",
      },
      {
        id: "grua-5000kg",
        name: "Dinamómetro / Báscula Aérea de 5 Toneladas",
        model: "Dialka CraneScale 5T",
        specs: "5.000 kg · Control remoto inalámbrico · Grillete forjado",
        badge: "Alta Capacidad Aérea",
        image: "/images/productos/ind-grua-5000kg.jpg",
      },
      {
        id: "indicador-x1s",
        name: "Indicador de Peso Digital Industrial",
        model: "Techfood X1S Inox",
        specs: "Acero Inoxidable · Puerto RS232 · Conexión impresora de tickets",
        badge: "Chasis Inoxidable",
        image: "/images/productos/techfood-indicador-x1s-inox.png",
      },
      {
        id: "software-weighmaster",
        name: "Software de Pesaje Camionero WeighMaster",
        model: "Dialka Software v2",
        specs: "Control de entradas/salidas, reportes en Excel, tickets con código QR",
        badge: "Desarrollo Propio",
        image: "/images/software/software-camiones.jpg",
      },
    ],
  },
];
